# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/api/user"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/auth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/auth/message"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/auth/post-confirmation"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/layer/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/layer/auth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/fn/layer/shared"
    schedule:
      interval: "weekly"
